=== abfeldman/lydia/testsuite/lydia_tests.dtd
<!-- A DTD for Lydia Testsuites -->

<!ELEMENT testsuite (test|separator)*>
<!ELEMENT test (skip?, title, model?, input?, output?, errors?, description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT input (#PCDATA)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT errors (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT skip EMPTY>

=== abfeldman/lydia/converters/lcm2wff/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>

  <separator>Basic Tests:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.lcm</input>
    <output>empty.hwff</output>
  </test>
  <test>
    <title>empty system</title>
    <input>realempty.lcm</input>
    <output>realempty.hwff</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.lcm</input>
    <output>basic_arrays.hwff</output>
  </test>

  <separator>Arithmetic Circuits (WFM):</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.lcm</input>
    <output>2inverters.hwff</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.lcm</input>
    <output>3inverters.hwff</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.lcm</input>
    <output>4inverters.hwff</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.lcm</input>
    <output>10inverters.hwff</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.lcm</input>
    <output>polycell.hwff</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.lcm</input>
    <output>2adder-weak.hwff</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.lcm</input>
    <output>2subtractor.hwff</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.lcm</input>
    <output>inverted-and.hwff</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.lcm</input>
    <output>74182.hwff</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.lcm</input>
    <output>74L85.hwff</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.lcm</input>
    <output>74283.hwff</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.lcm</input>
    <output>74181.hwff</output>
  </test>

  <separator>Arithmetic Circuits (SFM):</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.lcm</input>
    <output>2adder-strong.hwff</output>
  </test>

  <separator>Modelling Tests:</separator>
  <test>
    <title>copier</title>
    <input>copier.lcm</input>
    <output>copier.hwff</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.lcm</input>
    <output>stereo.hwff</output>
  </test>

  <separator>Observations:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.lco</input>
    <output>empty.obs.hwff</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.lco</input>
    <output>2inverters.obs.hwff</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.lco</input>
    <output>3inverters.obs.hwff</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.lco</input>
    <output>4inverters.obs.hwff</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder.lco</input>
    <output>2adder.obs.hwff</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.lco</input>
    <output>2subtractor.obs.hwff</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.lco</input>
    <output>polycell.obs.hwff</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.lco</input>
    <output>basic_arrays.obs.hwff</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.lco</input>
    <output>74182.obs.hwff</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.lco</input>
    <output>74L85.obs.hwff</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.lco</input>
    <output>74283.obs.hwff</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.lco</input>
    <output>74181.obs.hwff</output>
  </test>

  <separator>Regression Tests:</separator>
  <test>
    <title>issue 110</title>
    <input>issue110.lcm</input>
    <output>issue110.hwff</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/obdd2dnf/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Arithmetic Circuits (Flat):</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.obdd</input>
    <output>2inverters.dnf</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.obdd</input>
    <output>3inverters.dnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.obdd</input>
    <output>4inverters.dnf</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.obdd</input>
    <output>10inverters.dnf</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.obdd</input>
    <output>polycell.dnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.obdd</input>
    <output>2adder-weak.dnf</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.obdd</input>
    <output>2subtractor.dnf</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.obdd</input>
    <output>inverted-and.dnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.obdd</input>
    <output>2adder-strong.dnf</output>
  </test>
  <test>
    <title>copier</title>
    <input>copier.obdd</input>
    <output>copier.dnf</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.obdd</input>
    <output>stereo.dnf</output>
  </test>

  <separator>Arithmetic Circuits (Hierarchical):</separator>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hobdd</input>
    <output>polycell.hdnf</output>
  </test>

  <separator>Observations:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.obs.hobdd</input>
    <output>empty.terms</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.obs.hobdd</input>
    <output>2inverters.terms</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.obs.hobdd</input>
    <output>3inverters.terms</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.obs.hobdd</input>
    <output>4inverters.terms</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder.obs.hobdd</input>
    <output>2adder.terms</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.obs.hobdd</input>
    <output>2subtractor.terms</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.obs.hobdd</input>
    <output>polycell.terms</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.obs.hobdd</input>
    <output>basic_arrays.terms</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.obs.hobdd</input>
    <output>74182.terms</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.obs.hobdd</input>
    <output>74L85.terms</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.obs.hobdd</input>
    <output>74283.terms</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.obs.hobdd</input>
    <output>74181.terms</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/cnf2dnf/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>

  <separator>Basic Hierarhical Tests:</separator>
  <test>
    <title>empty system</title>
    <input>empty.hcnf</input>
    <output>empty.hdnf</output>
  </test>
  <test>
    <title>empty hierarchy</title>
    <input>realempty.hcnf</input>
    <output>realempty.hdnf</output>
  </test>

  <separator>Arithmetic Circuits (WFM) Hiearchical Tests:</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.hcnf</input>
    <output>2inverters.hdnf</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.hcnf</input>
    <output>3inverters.hdnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.hcnf</input>
    <output>4inverters.hdnf</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hcnf</input>
    <output>polycell.hdnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.hcnf</input>
    <output>2adder-weak.hdnf</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.hcnf</input>
    <output>2subtractor.hdnf</output>
  </test>

  <separator>Arithmetic Circuits (SFM) Hiearchical Tests:</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.hcnf</input>
    <output>2adder-strong.hdnf</output>
  </test>

  <separator>Basic Flat Tests:</separator>
  <test>
    <title>empty system</title>
    <input>empty.cnf</input>
    <output>empty.dnf</output>
  </test>
  <test>
    <title>realempty system</title>
    <input>realempty.cnf</input>
    <output>realempty.dnf</output>
  </test>

  <separator>Arithmetic Circuits (WFM) Flat Tests:</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.cnf</input>
    <output>2inverters.dnf</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.cnf</input>
    <output>3inverters.dnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.cnf</input>
    <output>4inverters.dnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.cnf</input>
    <output>2adder-weak.dnf</output>
  </test>

  <separator>Arithmetic Circuits (SFM) Flat Tests:</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.cnf</input>
    <output>2adder-strong.dnf</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/smoothy/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Basic Tests:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.lcm</input>
    <output>empty.csp</output>
  </test>
  <test>
    <title>empty system</title>
    <input>realempty.lcm</input>
    <output>realempty.csp</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.hcnf</input>
    <output>basic_arrays.cnf</output>
  </test>

  <separator>Basic CNF Tests:</separator>
  <test>
    <title>empty system</title>
    <input>empty.hcnf</input>
    <output>empty.cnf</output>
  </test>
  <test>
    <title>empty hierarchy</title>
    <input>realempty.hcnf</input>
    <output>realempty.cnf</output>
  </test>

  <separator>Propositional Wff Tests:</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.hwff</input>
    <output>2inverters.wff</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.hwff</input>
    <output>3inverters.wff</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.hwff</input>
    <output>4inverters.wff</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.hwff</input>
    <output>10inverters.wff</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hwff</input>
    <output>polycell.wff</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.hwff</input>
    <output>2adder-weak.wff</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.hwff</input>
    <output>2subtractor.wff</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.hwff</input>
    <output>inverted-and.wff</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.hwff</input>
    <output>2adder-strong.wff</output>
  </test>
  <test>
    <title>copier</title>
    <input>copier.hwff</input>
    <output>copier.wff</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.hwff</input>
    <output>stereo.wff</output>
  </test>

  <separator>Arithmetic Circuits (WFM) CNF Tests:</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.hcnf</input>
    <output>2inverters.cnf</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.hcnf</input>
    <output>3inverters.cnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.hcnf</input>
    <output>4inverters.cnf</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.hcnf</input>
    <output>10inverters.cnf</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hcnf</input>
    <output>polycell.cnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.hcnf</input>
    <output>2adder-weak.cnf</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.hcnf</input>
    <output>2subtractor.cnf</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.hcnf</input>
    <output>inverted-and.cnf</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.hcnf</input>
    <output>74182.cnf</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.hcnf</input>
    <output>74L85.cnf</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.hcnf</input>
    <output>74283.cnf</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.hcnf</input>
    <output>74181.cnf</output>
  </test>

  <separator>Arithmetic Circuits (SFM) CNF Tests:</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.hcnf</input>
    <output>2adder-strong.cnf</output>
  </test>
<!--
  <separator>Arithmetic Circuits (Custom Boolean Type):</separator>
  <test>
    <title>inverter</title>
    <input>inverter-mv.mvhcnf</input>
    <output>inverter-mv.mvcnf</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters-mv.mvhcnf</input>
    <output>2inverters-mv.mvcnf</output>
  </test>
-->
  <separator>Modelling Tests:</separator>
  <test>
    <title>copier</title>
    <input>copier.hcnf</input>
    <output>copier.cnf</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.hcnf</input>
    <output>stereo.cnf</output>
  </test>
<!--
  <separator>Mastermind:</separator>
  <test>
    <title>mastermind 2 pins, 3 colors</title>
    <input>mastermind-2x3.mvhcnf</input>
    <output>mastermind-2x3.mvcnf</output>
  </test>
  <test>
    <title>mastermind 2 pins, 4 colors</title>
    <input>mastermind-2x4.mvhcnf</input>
    <output>mastermind-2x4.mvcnf</output>
  </test>
  <test>
    <title>mastermind 2 pins, 5 colors</title>
    <input>mastermind-2x5.mvhcnf</input>
    <output>mastermind-2x5.mvcnf</output>
  </test>
  <test>
    <title>mastermind 2 pins, 6 colors</title>
    <input>mastermind-2x6.mvhcnf</input>
    <output>mastermind-2x6.mvcnf</output>
  </test>
  <test>
    <title>mastermind 3 pins, 3 colors</title>
    <input>mastermind-3x3.mvhcnf</input>
    <output>mastermind-3x3.mvcnf</output>
  </test>
  <test>
    <title>mastermind 3 pins, 4 colors</title>
    <input>mastermind-3x4.mvhcnf</input>
    <output>mastermind-3x4.mvcnf</output>
  </test>
  <test>
    <title>mastermind 3 pins, 5 colors</title>
    <input>mastermind-3x5.mvhcnf</input>
    <output>mastermind-3x5.mvcnf</output>
  </test>
  <test>
    <title>mastermind 3 pins, 6 colors</title>
    <input>mastermind-3x6.mvhcnf</input>
    <output>mastermind-3x6.mvcnf</output>
  </test>
  <test>
    <title>mastermind 4 pins, 3 colors</title>
    <input>mastermind-4x3.mvhcnf</input>
    <output>mastermind-4x3.mvcnf</output>
  </test>
  <test>
    <title>mastermind 4 pins, 4 colors</title>
    <input>mastermind-4x4.mvhcnf</input>
    <output>mastermind-4x4.mvcnf</output>
  </test>
  <test>
    <title>mastermind 4 pins, 5 colors</title>
    <input>mastermind-4x5.mvhcnf</input>
    <output>mastermind-4x5.mvcnf</output>
  </test>
  <test>
    <title>mastermind 4 pins, 6 colors</title>
    <input>mastermind-4x6.mvhcnf</input>
    <output>mastermind-4x6.mvcnf</output>
  </test>

  <separator>Sudoku:</separator>
  <test>
    <title>sudoku 4x4 grid (layout 1)</title>
    <input>sudoku-4x4-1.mvhcnf</input>
    <output>sudoku-4x4-1.mvcnf</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 1)</title>
    <input>sudoku-9x9-1.mvhcnf</input>
    <output>sudoku-9x9-1.mvcnf</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 2)</title>
    <input>sudoku-9x9-2.mvhcnf</input>
    <output>sudoku-9x9-2.mvcnf</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 3)</title>
    <input>sudoku-9x9-3.mvhcnf</input>
    <output>sudoku-9x9-3.mvcnf</output>
  </test>
-->
  <separator>Regression Tests:</separator>
<!--
  <test>
    <title>issue 41</title>
    <input>issue41.mvhcnf</input>
    <output>issue41.mvcnf</output>
  </test>
  <test>
    <title>issue 47</title>
    <input>issue47.mvhcnf</input>
    <output>issue47.mvcnf</output>
  </test>
-->
  <test>
    <title>issue 57</title>
    <input>issue57.hcsp</input>
    <output>issue57.csp</output>
  </test>
  <test>
    <title>issue 110</title>
    <input>issue110.hcnf</input>
    <output>issue110.cnf</output>
  </test>

  <separator>Arithmetic Circuits (SFM) DNF Tests:</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.hdnf</input>
    <output>2adder-strong.dnf</output>
  </test>

  <separator>Basic DNF Tests:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.hdnf</input>
    <output>empty.dnf</output>
  </test>
  <test>
    <title>empty system</title>
    <input>realempty.hdnf</input>
    <output>realempty.dnf</output>
  </test>

  <separator>Arithmetic Circuits DNF Tests:</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.hdnf</input>
    <output>2inverters.dnf</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.hdnf</input>
    <output>3inverters.dnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.hdnf</input>
    <output>4inverters.dnf</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hdnf</input>
    <output>polycell.dnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.hdnf</input>
    <output>2adder-weak.dnf</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.hdnf</input>
    <output>2subtractor.dnf</output>
  </test>
</testsuite>

=== abfeldman/lydia/tools/squeezy/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Arithmetic Circuits:</separator>
  <test>
    <title>1-bit full adder (hierarchical CNF)</title>
    <input>2adder-strong.hcnf</input>
    <output>2adder-strong.hcnf.sq</output>
  </test>
  <test>
    <title>1-bit full adder (hierarchical DNF)</title>
    <input>2adder-strong.hdnf</input>
    <output>2adder-strong.hdnf.sq</output>
  </test>
  <test>
    <title>1-bit full adder (flat CNF)</title>
    <input>2adder-strong.cnf</input>
    <output>2adder-strong.cnf.sq</output>
  </test>
  <test>
    <title>1-bit full adder (flat DNF)</title>
    <input>2adder-strong.dnf</input>
    <output>2adder-strong.dnf.sq</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/lcm2mvwff/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>

  <separator>Arithmetic Circuits (Custom Boolean Type):</separator>
  <test>
    <title>inverter</title>
    <input>inverter-mv.lcm</input>
    <output>inverter-mv.mvhwff</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters-mv.lcm</input>
    <output>2inverters-mv.mvhwff</output>
  </test>

  <separator>Mastermind:</separator>
  <test>
    <title>mastermind 2 pins, 3 colors</title>
    <input>mastermind-2x3.lcm</input>
    <output>mastermind-2x3.mvhwff</output>
  </test>
  <test>
    <title>mastermind 2 pins, 4 colors</title>
    <input>mastermind-2x4.lcm</input>
    <output>mastermind-2x4.mvhwff</output>
  </test>
  <test>
    <title>mastermind 2 pins, 5 colors</title>
    <input>mastermind-2x5.lcm</input>
    <output>mastermind-2x5.mvhwff</output>
  </test>
  <test>
    <title>mastermind 2 pins, 6 colors</title>
    <input>mastermind-2x6.lcm</input>
    <output>mastermind-2x6.mvhwff</output>
  </test>
  <test>
    <title>mastermind 3 pins, 3 colors</title>
    <input>mastermind-3x3.lcm</input>
    <output>mastermind-3x3.mvhwff</output>
  </test>
  <test>
    <title>mastermind 3 pins, 4 colors</title>
    <input>mastermind-3x4.lcm</input>
    <output>mastermind-3x4.mvhwff</output>
  </test>
  <test>
    <title>mastermind 3 pins, 5 colors</title>
    <input>mastermind-3x5.lcm</input>
    <output>mastermind-3x5.mvhwff</output>
  </test>
  <test>
    <title>mastermind 3 pins, 6 colors</title>
    <input>mastermind-3x6.lcm</input>
    <output>mastermind-3x6.mvhwff</output>
  </test>
  <test>
    <title>mastermind 4 pins, 3 colors</title>
    <input>mastermind-4x3.lcm</input>
    <output>mastermind-4x3.mvhwff</output>
  </test>
  <test>
    <title>mastermind 4 pins, 4 colors</title>
    <input>mastermind-4x4.lcm</input>
    <output>mastermind-4x4.mvhwff</output>
  </test>
  <test>
    <title>mastermind 4 pins, 5 colors</title>
    <input>mastermind-4x5.lcm</input>
    <output>mastermind-4x5.mvhwff</output>
  </test>
  <test>
    <title>mastermind 4 pins, 6 colors</title>
    <input>mastermind-4x6.lcm</input>
    <output>mastermind-4x6.mvhwff</output>
  </test>

  <separator>Sudoku:</separator>
  <test>
    <title>sudoku 4x4 grid (layout 1)</title>
    <input>sudoku-4x4-1.lcm</input>
    <output>sudoku-4x4-1.mvhwff</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 1)</title>
    <input>sudoku-9x9-1.lcm</input>
    <output>sudoku-9x9-1.mvhwff</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 2)</title>
    <input>sudoku-9x9-2.lcm</input>
    <output>sudoku-9x9-2.mvhwff</output>
  </test>
  <test>
    <title>sudoku 9x9 grid (layout 3)</title>
    <input>sudoku-9x9-3.lcm</input>
    <output>sudoku-9x9-3.mvhwff</output>
  </test>

  <separator>Regression Tests:</separator>
  <test>
    <title>issue 41</title>
    <input>issue41.lcm</input>
    <output>issue41.mvhwff</output>
  </test>
  <test>
    <title>issue 42</title>
    <input>issue42.lcm</input>
    <output>issue42.mvhwff</output>
  </test>
  <test>
    <title>issue 47</title>
    <input>issue47.lcm</input>
    <output>issue47.mvhwff</output>
  </test>
  <test>
    <title>issue 81</title>
    <input>issue81.lcm</input>
    <output>issue81.mvhwff</output>
  </test>
  <test>
    <title>issue 133</title>
    <input>issue133.lcm</input>
    <output>issue133.mvhwff</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/wff2cnf/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>

  <separator>Basic Tests:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.hwff</input>
    <output>empty.hcnf</output>
  </test>
  <test>
    <title>empty system</title>
    <input>realempty.hwff</input>
    <output>realempty.hcnf</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.hwff</input>
    <output>basic_arrays.hcnf</output>
  </test>

  <separator>Arithmetic Circuits Flat Tests:</separator>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.wff</input>
    <output>polycell.cnf</output>
  </test>

  <separator>Arithmetic Circuits (WFM):</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.hwff</input>
    <output>2inverters.hcnf</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.hwff</input>
    <output>3inverters.hcnf</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.hwff</input>
    <output>4inverters.hcnf</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.hwff</input>
    <output>10inverters.hcnf</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hwff</input>
    <output>polycell.hcnf</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.hwff</input>
    <output>2adder-weak.hcnf</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.hwff</input>
    <output>2subtractor.hcnf</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.hwff</input>
    <output>inverted-and.hcnf</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.hwff</input>
    <output>74182.hcnf</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.hwff</input>
    <output>74L85.hcnf</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.hwff</input>
    <output>74283.hcnf</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.hwff</input>
    <output>74181.hcnf</output>
  </test>

  <separator>Arithmetic Circuits (SFM):</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.hwff</input>
    <output>2adder-strong.hcnf</output>
  </test>

  <separator>Modelling Tests:</separator>
  <test>
    <title>copier</title>
    <input>copier.hwff</input>
    <output>copier.hcnf</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.hwff</input>
    <output>stereo.hcnf</output>
  </test>

  <separator>Regression Tests:</separator>
  <test>
    <title>issue 110</title>
    <input>issue110.hwff</input>
    <output>issue110.hcnf</output>
  </test>
</testsuite>

=== abfeldman/lydia/lang/oc/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <test>
    <title>empty observation</title>
    <model>empty.lcm</model>
    <observation>empty.obs</observation>
    <output>empty.lco</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <model>2inverters.lcm</model>
    <observation>2inverters.obs</observation>
    <output>2inverters.lco</output>
  </test>
  <test>
    <title>3 inverters</title>
    <model>3inverters.lcm</model>
    <observation>3inverters.obs</observation>
    <output>3inverters.lco</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <model>4inverters.lcm</model>
    <observation>4inverters.obs</observation>
    <output>4inverters.lco</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <model>2adder-weak.lcm</model>
    <observation>2adder.obs</observation>
    <output>2adder.lco</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <model>2subtractor.lcm</model>
    <observation>2subtractor.obs</observation>
    <output>2subtractor.lco</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <model>polycell.lcm</model>
    <observation>polycell.obs</observation>
    <output>polycell.lco</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <model>basic_arrays.lcm</model>
    <observation>basic_arrays.obs</observation>
    <output>basic_arrays.lco</output>
  </test>
  <test>
    <title>74182</title>
    <model>74182.lcm</model>
    <observation>74182.obs</observation>
    <output>74182.lco</output>
  </test>
  <test>
    <title>74L85</title>
    <model>74L85.lcm</model>
    <observation>74L85.obs</observation>
    <output>74L85.lco</output>
  </test>
  <test>
    <title>74283</title>
    <model>74283.lcm</model>
    <observation>74283.obs</observation>
    <output>74283.lco</output>
  </test>
  <test>
    <title>74181</title>
    <model>74181.lcm</model>
    <observation>74181.obs</observation>
    <output>74181.lco</output>
  </test>
</testsuite>
