=== abfeldman/lydia/testsuite/lydia_tests.dtd
<!-- A DTD for Lydia Testsuites -->

<!ELEMENT testsuite (test|separator)*>
<!ELEMENT test (skip?, title, model?, input?, output?, errors?, description?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT input (#PCDATA)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT errors (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT skip EMPTY>

=== abfeldman/lydia/converters/cnf2horn/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Arithmetic Circuits (WFM) Flat Tests:</separator>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.cnf</input>
    <output>2adder-weak.atms</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.cnf</input>
    <output>74182.atms</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.cnf</input>
    <output>74L85.atms</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.cnf</input>
    <output>74283.atms</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.cnf</input>
    <output>74181.atms</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/mvwff2tvwff/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Arithmetic Circuits:</separator>
  <test>
    <title>inverter</title>
    <input>inverter-mv.mvhwff</input>
    <output>inverter-mv.hwff</output>
  </test>

  <separator>Regression Tests:</separator>
  <test>
    <title>issue 81</title>
    <input>issue81.mvhwff</input>
    <output>issue81.hwff</output>
  </test>
  <test>
    <title>issue 133</title>
    <input>issue133.mvhwff</input>
    <output>issue133.hwff</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/cnf2dnf/tests/stress.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <test>
    <title>polycell-flat</title>
    <input>polycell.cnf</input>
    <output>polycell.dnf</output>
  </test>
  <test>
    <title>2subtractor-flat</title>
    <input>2subtractor.cnf</input>
    <output>2subtractor.dnf</output>
  </test>
</testsuite>

=== abfeldman/lydia/converters/wff2obdd/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../testsuite/lydia_tests.dtd">

<testsuite>
  <separator>Arithmetic Circuits (Flat):</separator>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.wff</input>
    <output>2inverters.obdd</output>
  </test>
  <test>
    <title>3 chained inverters</title>
    <input>3inverters.wff</input>
    <output>3inverters.obdd</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.wff</input>
    <output>4inverters.obdd</output>
  </test>
  <test>
    <title>10 chained inverters</title>
    <input>10inverters.wff</input>
    <output>10inverters.obdd</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.wff</input>
    <output>polycell.obdd</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-weak.wff</input>
    <output>2adder-weak.obdd</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.wff</input>
    <output>2subtractor.obdd</output>
  </test>
  <test>
    <title>3 inverters and an AND gate</title>
    <input>inverted-and.wff</input>
    <output>inverted-and.obdd</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder-strong.wff</input>
    <output>2adder-strong.obdd</output>
  </test>
  <test>
    <title>copier</title>
    <input>copier.wff</input>
    <output>copier.obdd</output>
  </test>
  <test>
    <title>stereo</title>
    <input>stereo.wff</input>
    <output>stereo.obdd</output>
  </test>

  <separator>Arithmetic Circuits (Hierarchical):</separator>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.hwff</input>
    <output>polycell.hobdd</output>
  </test>

  <separator>Observations:</separator>
  <test>
    <title>empty hierarchy</title>
    <input>empty.obs.hwff</input>
    <output>empty.obs.hobdd</output>
  </test>
  <test>
    <title>2 chained inverters</title>
    <input>2inverters.obs.hwff</input>
    <output>2inverters.obs.hobdd</output>
  </test>
  <test>
    <title>3 inverters</title>
    <input>3inverters.obs.hwff</input>
    <output>3inverters.obs.hobdd</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <input>4inverters.obs.hwff</input>
    <output>4inverters.obs.hobdd</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <input>2adder.obs.hwff</input>
    <output>2adder.obs.hobdd</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <input>2subtractor.obs.hwff</input>
    <output>2subtractor.obs.hobdd</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <input>polycell.obs.hwff</input>
    <output>polycell.obs.hobdd</output>
  </test>
  <test>
    <title>basic array expressions</title>
    <input>basic_arrays.obs.hwff</input>
    <output>basic_arrays.obs.hobdd</output>
  </test>
  <test>
    <title>74182</title>
    <input>74182.obs.hwff</input>
    <output>74182.obs.hobdd</output>
  </test>
  <test>
    <title>74L85</title>
    <input>74L85.obs.hwff</input>
    <output>74L85.obs.hobdd</output>
  </test>
  <test>
    <title>74283</title>
    <input>74283.obs.hwff</input>
    <output>74283.obs.hobdd</output>
  </test>
  <test>
    <title>74181</title>
    <input>74181.obs.hwff</input>
    <output>74181.obs.hobdd</output>
  </test>

</testsuite>

=== abfeldman/lydia/solvers/gotcha/tests/tests.xml
<?xml version="1.0" encoding="iso-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "../../../../testsuite/lydia_tests.dtd">

<testsuite>
  <test>
    <title>empty system</title>
    <model>empty.hdnf</model>
    <input>empty.commands.input</input>
    <observation>empty.terms</observation>
    <output>empty.expected.out</output>
  </test>
  <test>
    <title>empty hierarchy</title>
    <model>realempty.hdnf</model>
    <observation>empty.terms</observation>
    <errors>realempty.expected.err</errors>
  </test>
  <test>
    <title>2 chained inverters</title>
    <model>2inverters.hdnf</model> 
    <input>2inverters.commands.input</input>
    <observation>2inverters.terms</observation>
    <output>2inverters.expected.out</output>
  </test>
  <test>
    <title>3 inverters</title>
    <model>3inverters.hdnf</model>
    <input>3inverters.commands.input</input>
    <observation>3inverters.terms</observation>
    <output>3inverters.expected.out</output>
  </test>
  <test>
    <title>4 chained inverters</title>
    <model>4inverters.hdnf</model>
    <input>4inverters.commands.input</input>
    <observation>4inverters.terms</observation>
    <output>4inverters.expected.out</output>
  </test>
  <test>
    <title>Boolean polycell</title>
    <model>polycell.hdnf</model>
    <input>polycell.commands.input</input>
    <observation>polycell.terms</observation>
    <output>polycell.expected.out</output>
  </test>
  <test>
    <title>1-bit full adder</title>
    <model>2adder-weak.hdnf</model>
    <input>2adder.commands.input</input>
    <observation>2adder.terms</observation>
    <output>2adder-weak.expected.out</output>
  </test>
  <test>
    <title>1-bit subtractor</title>
    <model>2subtractor.hdnf</model>
    <input>2subtractor.commands.input</input>
    <observation>2subtractor.terms</observation>
    <output>2subtractor.expected.out</output>
  </test>

</testsuite>
